language: csharp
sudo: false
dist: trusty
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
script:
  - dotnet --info
  - dotnet restore ChaosCMS.sln
  - dotnet build ChaosCMS.sln -c Release
  - dotnet test test/ChaosCMS.Test/ChaosCMS.Test.csproj -c Release