language: csharp
mono: none
dist: trusty
sudo: required
env:
  global:
    - DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
    - DOTNET_CLI_TELEMETRY_OPTOUT: 1
  - CLI_VERSION=latest
addons:
  apt:
    packages:
      - libunwind8
mono: none
os:
  - linux
  - osx
osx_image: xcode8.2

branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
before_install:
  - if test "$TRAVIS_OS_NAME" == "osx"; then brew update; brew install openssl; ln -s /usr/local/opt/openssl/lib/libcrypto.1.0.0.dylib /usr/local/lib/; ln -s /usr/local/opt/openssl/lib/libssl.1.0.0.dylib /usr/local/lib/; fi
install:  
  - export DOTNET_INSTALL_DIR="$PWD/.dotnetcli"
  - curl -sSL https://raw.githubusercontent.com/dotnet/cli/rel/1.0.0/scripts/obtain/dotnet-install.sh | bash /dev/stdin --version "$CLI_VERSION" --install-dir "$DOTNET_INSTALL_DIR"
  - export PATH="$DOTNET_INSTALL_DIR:$PATH"  
script:
  - dotnet --info
  - dotnet restore ChaosCMS.sln
  - dotnet build ChaosCMS.sln -c Release
  - dotnet test test/ChaosCMS.Test/ChaosCMS.Test.csproj -c Release