language: csharp
mono: none
dotnet: 1.0.4
dist: trust
sudo: required
branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/

script:
  - dotnet --info
  - dotnet restore ChaosCMS.sln
  - dotnet build ChaosCMS.sln -c Release
  - dotnet test test/ChaosCMS.Test/ChaosCMS.Test.csproj -c Release