branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
install:
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
build_script:
  - dotnet --info
  - dotnet restore ChaosCMS.sln
  - dotnet build ChaosCMS.sln -c Release
clone_depth: 1
test_script:
  - dotnet test test/ChaosCMS.Test/ChaosCMS.Test.csproj -c Release
artifacts:
- path: /artifacts/build/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: 82jTc4+tKUmxGnoGfBH1lGkx98G/oE13jaw18hHt2DMcJsF2wGSS6caxNg/6tvN+
  skip_symbols: false
  on:
      branch: master
image: Visual Studio 2017