branches:
  only:
    - master
    - release
    - develop
    - /^(.*\/)?ci-.*$/
environment:
  nodejs_version: "6"
# Install scripts. (runs after repo cloning)
install:
  # Make sure curl is available
  - set PATH=C:\Program Files\Git\mingw64\bin;%PATH%
  # add dotnet to PATH
   - ps: $env:Path = "$env:DOTNET_INSTALL_DIR;$env:Path"
  # Get the latest stable version of Node.js or io.js
  #- ps: Install-Product node $env:nodejs_version
  # - GitVersion
  # install modules
  #- npm --version {build}
  #- npm install
  #- npm install webpack -g
build_script:
  #- webpack
  - dotnet --info
  - dotnet restore ChaosCMS.sln
  - dotnet build ChaosCMS.sln -c Release
clone_depth: 1
test_script:
  - dotnet test test/ChaosCMS.Test/ChaosCMS.Test.csproj -c Release
artifacts:
- path: /artifacts/build/*.nupkg
deploy:
  provider: NuGet
  api_key:
    secure: 82jTc4+tKUmxGnoGfBH1lGkx98G/oE13jaw18hHt2DMcJsF2wGSS6caxNg/6tvN+
  skip_symbols: false
  on:
      branch: master
image: Visual Studio 2017