// <auto-generated />
namespace ChaosCMS
{
    using System.Globalization;
    using System.Reflection;
    using System.Resources;

    internal static class Resources
    {
        private static readonly ResourceManager _resourceManager
            = new ResourceManager("ChaosCMS.Resources", typeof(Resources).GetTypeInfo().Assembly);

        /// <summary>
        /// An unknown failure has occurred.
        /// </summary>
        internal static string DefaultError
        {
            get { return GetString("DefaultError"); }
        }

        /// <summary>
        /// AddChaos must be called on the service collection.
        /// </summary>
        internal static string MustCallAddChaos
        {
            get { return GetString("MustCallAddChaos"); }
        }

        /// <summary>
        /// There is not page found at '{0}'.
        /// </summary>
        internal static string PageNotFound
        {
            get { return GetString("PageNotFound"); }
        }

        /// <summary>
        /// There is not page found at '{0}'.
        /// </summary>
        internal static string FormatPageNotFound(object p0)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("PageNotFound"), p0);
        }

        /// <summary>
        /// Type {0} must derive from {1}&lt;{2}&gt;.
        /// </summary>
        internal static string InvalidManagerType
        {
            get { return GetString("InvalidManagerType"); }
        }

        /// <summary>
        /// Type {0} must derive from {1}&lt;{2}&gt;.
        /// </summary>
        internal static string FormatInvalidManagerType(object p0, object p1, object p2)
        {
            return string.Format(CultureInfo.CurrentCulture, GetString("InvalidManagerType"), p0, p1, p2);
        }

        private static string GetString(string name, params string[] formatterNames)
        {
            var value = _resourceManager.GetString(name);

            System.Diagnostics.Debug.Assert(value != null);

            if (formatterNames != null)
            {
                for (var i = 0; i < formatterNames.Length; i++)
                {
                    value = value.Replace("{" + formatterNames[i] + "}", "{" + i + "}");
                }
            }

            return value;
        }
    }
}